# Generated by Django 4.1.2 on 2022-10-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equestion',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
