# Generated by Django 4.1.2 on 2022-11-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skil', '0002_equestion_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equestion',
            name='number',
        ),
    ]
