# Generated by Django 4.1.2 on 2022-11-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skil', '0003_remove_equestion_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='equestion',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
