# Generated by Django 4.1.2 on 2022-11-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skil', '0004_equestion_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equestion',
            name='number',
        ),
        migrations.AlterField(
            model_name='equestion',
            name='answer',
            field=models.IntegerField(default=0),
        ),
    ]
