# Generated by Django 4.1.2 on 2022-11-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skil', '0008_alter_equestion_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equestion',
            name='answer',
            field=models.IntegerField(),
        ),
    ]
