# Generated by Django 4.1.2 on 2022-11-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skil', '0011_alter_nquestion_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equestion',
            name='answer',
            field=models.TextField(),
        ),
    ]
