# Generated by Django 4.1.2 on 2022-11-05 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skil', '0012_alter_equestion_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percent',
            name='ques',
        ),
    ]
