# Generated by Django 4.1.2 on 2022-11-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skil', '0014_percent_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.TextField()),
                ('true', models.IntegerField(default=0)),
                ('false', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Npercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.TextField()),
                ('true', models.IntegerField(default=0)),
                ('false', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Percent',
        ),
    ]
