# Generated by Django 4.1.2 on 2022-11-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skil', '0015_epercent_npercent_delete_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='epercent',
            name='percent',
            field=models.FloatField(default=0),
        ),
    ]
