# Generated by Django 4.1.2 on 2022-11-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skil', '0016_epercent_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epercent',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
