# Generated by Django 4.1.2 on 2022-11-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skil', '0017_alter_epercent_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='npercent',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
